trigger:
- main
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_BUILDKIT: 1
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    imageTag: '$(Build.BuildId)'
    appServiceName: 'myfeatures'
    BUILD_ENV: 'production'  # Angular build env
    DOTNET_ENV: 'Production' # .NET environment
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/development') }}:
    imageTag: 'dev'
    appServiceName: 'myfeaturesdev'
    BUILD_ENV: 'staging'    # Angular build env
    DOTNET_ENV: 'Staging'   # .NET environment

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        containerRegistry: 'my-service-connection'
        command: 'login'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: 'my-service-connection'
        repository: 'myfeaturescontainerregistry/acr-repository-3'
        command: 'build'
        Dockerfile: 'Dockerfile'
        buildContext: '.'
        arguments: '--build-arg BUILD_ENV=$(BUILD_ENV)'
        tags: |
          $(imageTag)

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        containerRegistry: 'my-service-connection'
        repository: 'myfeaturescontainerregistry/acr-repository-3'
        command: 'push'
        tags: |
          $(imageTag)

- stage: Deploy
  condition: succeeded()
  jobs:
  - job: DeployWebApp
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'arm-service-connection'
        appName: '$(appServiceName)'
        containers: 'myfeaturescontainerregistry.azurecr.io/myfeaturescontainerregistry/acr-repository-3:$(imageTag)'
