trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_BUILDKIT: 1
  # Define different tags for main and develop branches
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    imageTag: '$(Build.BuildId)'  # Unique tag for production
    appServiceName: 'myfeatures'   # Production App Service name
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    imageTag: 'dev'                # Static tag for development
    appServiceName: 'myfeaturesdev' # Development App Service name

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        containerRegistry: 'my-service-connection'
        command: 'login'

    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: 'my-service-connection'
        repository: 'myfeaturescontainerregistry/acr-repository-3'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: |
          $(imageTag)

- stage: Deploy
  condition: succeeded()
  jobs:
  - job: DeployWebApp
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'arm-service-connection'
        appName: '$(appServiceName)'
        containers: 'myfeaturescontainerregistry/acr-repository-3:$(imageTag)'
